name: floorp
base: core22
version: "latest"
title: Floorp Browser
summary: Browse the web with Floorp
description: |
  Floorp is a highly customizable browser derived from Firefox. This snap repackages the upstream Linux build.
grade: stable
confinement: strict
icon: snap/gui/floorp.png

contact: https://github.com/Floorp-Projects/Floorp/issues
website: https://floorp.app/
source-code: https://github.com/Floorp-Projects/Floorp
issues: https://github.com/Floorp-Projects/Floorp/issues
license: MPL-2.0
donation: https://floorp.app/donate

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  floorp:
    plugin: dump
    source: https://github.com/Floorp-Projects/Floorp/releases/latest/download/floorp-linux-amd64.tar.xz
    source-type: tar

    build-packages:
      - execstack
      - binutils

    override-pull: |
      craftctl default

    override-build: |
      craftctl default

      install -Dm0644 /dev/stdin "$CRAFT_PART_INSTALL/usr/share/applications/floorp.desktop" <<'EOF'
      [Desktop Entry]
      Name=Floorp
      Comment=Browse the Web
      Exec=floorp %U
      Icon=${SNAP}/meta/gui/floorp.png
      Terminal=false
      Type=Application
      Categories=Network;WebBrowser;
      MimeType=text/html;x-scheme-handler/http;x-scheme-handler/https;
      StartupWMClass=Floorp
      EOF

      ACTUAL_BIN="$(find "$CRAFT_PART_INSTALL" -type f \( -name floorp -o -name floorp-bin \) -perm -111 | head -n1 || true)"
      if [ -z "$ACTUAL_BIN" ]; then
        echo "ERROR: Could not find Floorp binary in $CRAFT_PART_INSTALL" >&2
        find "$CRAFT_PART_INSTALL" -maxdepth 3 -printf '%P\n' >&2
        exit 1
      fi
      REL_PATH="${ACTUAL_BIN#"$CRAFT_PART_INSTALL/"}"
      install -Dm0755 /dev/stdin "$CRAFT_PART_INSTALL/bin/floorp-launch" <<EOF
      #!/bin/sh
      exec "\$SNAP/$REL_PATH" "\$@"
      EOF

      if command -v execstack >/dev/null 2>&1; then
        while IFS= read -r -d '' so; do
          if execstack -q "$so" 2>/dev/null | grep -q '^X'; then
            echo "Clearing execstack: $so"
            execstack -c "$so" || { echo "Failed to clear execstack on $so"; exit 1; }
          fi
        done < <(find "$CRAFT_PART_INSTALL" -type f -name '*.so*' -print0)
      fi

    stage-packages:
      - libasound2
      - libnspr4
      - libnss3

    stage:
      - "**"
      - bin/floorp-launch
      - usr/share/applications/floorp.desktop

apps:
  floorp:
    command: bin/floorp-launch
    desktop: usr/share/applications/floorp.desktop
    extensions: [gnome]
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - network
      - opengl
      - x11
      - wayland
      - desktop
      - gsettings
      - audio-playback
      - pulseaudio
      - alsa
      - camera
      - audio-record
      - password-manager-service
      - u2f-devices
      - pcscd
      - removable-media
      - screen-inhibit-control
      - upower-observe
      - bluez
      - cups-control
      - avahi-observe
      - joystick
      - mount-observe

slots:
  floorp-mpris:
    interface: mpris
    name: floorp